// Inbound verifier presets. AgentMail uses Svix headers per:
// https://docs.agentmail.to/webhook-verification and
// https://www.svix.com/guides/receiving/receive-webhooks-with-svix-cli/
export const WEBHOOK_PRESETS = [
  {
    label: 'Standard Webhooks',
    auth_scheme: 'hmac_sha256',
    verifier_mode: 'hmac_v2',
    signature_header: 'webhook-signature',
    signature_algo: 'sha256',
    signature_encoding: 'base64',
    signature_prefix: 'v1,',
    signature_separator: ' ',
    signature_value_split: ',',
    timestamp_header: 'webhook-timestamp',
    timestamp_skew_secs: 300,
    payload_template: '{{id}}.{{timestamp}}.{{body}}',
    idempotency_header: 'webhook-id',
  },
  {
    label: 'GitHub',
    auth_scheme: 'hmac_sha256',
    verifier_mode: 'hmac_v2',
    signature_header: 'x-hub-signature-256',
    signature_algo: 'sha256',
    signature_encoding: 'hex',
    signature_prefix: 'sha256=',
    signature_separator: '',
    signature_value_split: '=',
    timestamp_header: '',
    timestamp_skew_secs: 300,
    payload_template: '{{body}}',
    idempotency_header: 'x-github-delivery',
  },
  {
    label: 'Stripe',
    auth_scheme: 'hmac_sha256',
    verifier_mode: 'hmac_v2',
    signature_header: 'stripe-signature',
    signature_algo: 'sha256',
    signature_encoding: 'hex',
    signature_prefix: 'v1=',
    signature_separator: ',',
    signature_value_split: '=',
    timestamp_header: 'stripe-signature',
    timestamp_skew_secs: 300,
    payload_template: '{{timestamp}}.{{body}}',
    idempotency_header: '',
  },
  {
    label: 'Slack',
    auth_scheme: 'hmac_sha256',
    verifier_mode: 'hmac_v2',
    signature_header: 'x-slack-signature',
    signature_algo: 'sha256',
    signature_encoding: 'hex',
    signature_prefix: 'v0=',
    signature_separator: '',
    signature_value_split: '=',
    timestamp_header: 'x-slack-request-timestamp',
    timestamp_skew_secs: 300,
    payload_template: 'v0:{{timestamp}}:{{body}}',
    idempotency_header: '',
  },
  {
    label: 'Shopify',
    auth_scheme: 'hmac_sha256',
    verifier_mode: 'hmac_v2',
    signature_header: 'x-shopify-hmac-sha256',
    signature_algo: 'sha256',
    signature_encoding: 'base64',
    signature_prefix: '',
    signature_separator: '',
    signature_value_split: '',
    timestamp_header: '',
    timestamp_skew_secs: 300,
    payload_template: '{{body}}',
    idempotency_header: 'x-shopify-webhook-id',
  },
  {
    label: 'AgentMail',
    auth_scheme: 'hmac_sha256',
    verifier_mode: 'hmac_v2',
    signature_header: 'svix-signature',
    signature_algo: 'sha256',
    signature_encoding: 'base64',
    signature_prefix: 'v1,',
    signature_separator: ' ',
    signature_value_split: ',',
    timestamp_header: 'svix-timestamp',
    timestamp_skew_secs: 300,
    payload_template: '{{id}}.{{timestamp}}.{{body}}',
    idempotency_header: 'svix-id',
  },
];
