use std::collections::{BTreeMap, BTreeSet};
use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};

use sha2::{Digest, Sha256};

fn main() {
    println!("cargo:rerun-if-changed=migrations/sqlite");
    println!("cargo:rerun-if-changed=migrations/postgres");
    println!("cargo:rerun-if-changed=migrations/equivalence.toml");

    let out_dir = PathBuf::from(std::env::var_os("OUT_DIR").expect("OUT_DIR set"));
    let out_path = out_dir.join("migration_parity.rs");

    let sqlite = match read_migrations(Path::new("migrations/sqlite")) {
        Ok(v) => v,
        Err(err) => {
            write_compile_error(&out_path, &format!("read sqlite migrations: {err}"));
            return;
        }
    };
    let postgres = match read_migrations(Path::new("migrations/postgres")) {
        Ok(v) => v,
        Err(err) => {
            write_compile_error(&out_path, &format!("read postgres migrations: {err}"));
            return;
        }
    };
    let equivalence = match read_equivalence(Path::new("migrations/equivalence.toml")) {
        Ok(v) => v,
        Err(err) => {
            write_compile_error(&out_path, &format!("read migration equivalence: {err}"));
            return;
        }
    };

    let sqlite_names: Vec<_> = sqlite.keys().cloned().collect();
    let pg_names: Vec<_> = postgres.keys().cloned().collect();
    if sqlite_names != pg_names {
        let sqlite_set: BTreeSet<_> = sqlite_names.iter().cloned().collect();
        let pg_set: BTreeSet<_> = pg_names.iter().cloned().collect();
        let missing_pg: Vec<_> = sqlite_set.difference(&pg_set).cloned().collect();
        let missing_sqlite: Vec<_> = pg_set.difference(&sqlite_set).cloned().collect();
        let msg = format!(
            "migration parity failed; missing postgres migrations: [{}]; missing sqlite migrations: [{}]",
            missing_pg.join(", "),
            missing_sqlite.join(", ")
        );
        println!("cargo:warning={msg}");
        write_compile_error(&out_path, &msg);
        return;
    }

    let mut rows = Vec::new();
    let mut strict_mismatches = Vec::new();
    let mut stale_equivalence = Vec::new();
    for (name, sqlite_sql) in &sqlite {
        let pg_sql = postgres
            .get(name)
            .expect("migration name parity already checked");
        let sqlite_hash = hash_sql(sqlite_sql);
        let pg_hash = hash_sql(pg_sql);
        if sqlite_hash != pg_hash {
            match equivalence.get(name) {
                Some(expected)
                    if expected.sqlite == sqlite_hash && expected.postgres == pg_hash => {}
                Some(_) => stale_equivalence.push(name.clone()),
                None => strict_mismatches.push(name.clone()),
            }
        }
        rows.push((name.clone(), sqlite_hash, pg_hash));
    }

    if !strict_mismatches.is_empty() {
        let msg = format!(
            "migration SQL parity failed; dialect-different migrations need entries in migrations/equivalence.toml: {}",
            strict_mismatches.join(", ")
        );
        println!("cargo:warning={msg}");
        write_compile_error(&out_path, &msg);
        return;
    }
    if !stale_equivalence.is_empty() {
        let msg = format!(
            "migration equivalence fingerprints changed; update migrations/equivalence.toml after reviewing logical schema parity: {}",
            stale_equivalence.join(", ")
        );
        println!("cargo:warning={msg}");
        write_compile_error(&out_path, &msg);
        return;
    }

    let mut src = String::new();
    src.push_str("// @generated by build.rs; do not edit by hand.\n");
    src.push_str("#[allow(dead_code)]\n");
    src.push_str("pub const MIGRATION_FINGERPRINTS: &[(&str, [u8; 32], [u8; 32])] = &[\n");
    for (name, sqlite_hash, pg_hash) in rows {
        src.push_str("    (");
        push_rust_string(&mut src, &name);
        src.push_str(", ");
        push_hash(&mut src, sqlite_hash);
        src.push_str(", ");
        push_hash(&mut src, pg_hash);
        src.push_str("),\n");
    }
    src.push_str("];\n\n");
    src.push_str("#[allow(dead_code)]\n");
    src.push_str("pub const fn assert_parity() {}\n");
    src.push_str("const _: () = assert_parity();\n");
    fs::write(&out_path, src).expect("write migration parity include");
}

fn read_migrations(dir: &Path) -> std::io::Result<BTreeMap<String, String>> {
    let mut entries = Vec::new();
    for entry in fs::read_dir(dir)? {
        let entry = entry?;
        let path = entry.path();
        if path.extension().and_then(|s| s.to_str()) != Some("sql") {
            continue;
        }
        let file_name = path
            .file_name()
            .and_then(|s| s.to_str())
            .unwrap_or_default()
            .to_owned();
        entries.push((file_name, path));
    }
    entries.sort_by(|a, b| a.0.cmp(&b.0));

    let mut migrations = BTreeMap::new();
    let mut ordered = Vec::new();
    for (file_name, path) in entries {
        let Some(logical) = logical_name(&file_name) else {
            continue;
        };
        let sql = fs::read_to_string(path)?;
        ordered.push((logical, sql));
    }
    for (logical, sql) in ordered {
        migrations.insert(logical, sql);
    }
    Ok(migrations)
}

fn logical_name(file_name: &str) -> Option<String> {
    let (prefix, rest) = file_name.split_once('_')?;
    if prefix.len() == 4 && prefix.chars().all(|c| c.is_ascii_digit()) {
        return Some(rest.trim_end_matches(".sql").to_owned());
    }
    None
}

#[derive(Debug, Clone, Copy)]
struct ExpectedFingerprint {
    sqlite: [u8; 32],
    postgres: [u8; 32],
}

fn read_equivalence(path: &Path) -> Result<BTreeMap<String, ExpectedFingerprint>, String> {
    if !path.exists() {
        return Ok(BTreeMap::new());
    }
    let raw = fs::read_to_string(path).map_err(|e| e.to_string())?;
    let parsed: toml::Value = raw.parse::<toml::Value>().map_err(|e| e.to_string())?;
    let mut out = BTreeMap::new();
    let Some(table) = parsed.get("equivalence").and_then(toml::Value::as_table) else {
        return Ok(out);
    };
    for (name, value) in table {
        let Some(item) = value.as_table() else {
            return Err(format!("equivalence.{name} must be a table"));
        };
        let sqlite = item
            .get("sqlite")
            .and_then(toml::Value::as_str)
            .ok_or_else(|| format!("equivalence.{name}.sqlite is required"))?;
        let postgres = item
            .get("postgres")
            .and_then(toml::Value::as_str)
            .ok_or_else(|| format!("equivalence.{name}.postgres is required"))?;
        out.insert(
            name.clone(),
            ExpectedFingerprint {
                sqlite: parse_hex_hash(name, "sqlite", sqlite)?,
                postgres: parse_hex_hash(name, "postgres", postgres)?,
            },
        );
    }
    Ok(out)
}

fn parse_hex_hash(name: &str, side: &str, raw: &str) -> Result<[u8; 32], String> {
    if raw.len() != 64 {
        return Err(format!(
            "equivalence.{name}.{side} must be a 64-character sha256 hex digest"
        ));
    }
    let mut out = [0u8; 32];
    for (idx, chunk) in raw.as_bytes().chunks_exact(2).enumerate() {
        let text = std::str::from_utf8(chunk).map_err(|e| e.to_string())?;
        out[idx] = u8::from_str_radix(text, 16)
            .map_err(|_| format!("equivalence.{name}.{side} contains non-hex bytes"))?;
    }
    Ok(out)
}

fn hash_sql(sql: &str) -> [u8; 32] {
    let mut normalized = String::new();
    for line in sql.lines() {
        let line = line.split("--").next().unwrap_or_default();
        normalized.push_str(line);
        normalized.push('\n');
    }
    let normalized = normalized
        .split_whitespace()
        .collect::<Vec<_>>()
        .join(" ")
        .to_lowercase();
    Sha256::digest(normalized.as_bytes()).into()
}

fn push_hash(src: &mut String, hash: [u8; 32]) {
    src.push('[');
    for (idx, byte) in hash.iter().enumerate() {
        if idx > 0 {
            src.push_str(", ");
        }
        let _ = write!(src, "0x{byte:02x}");
    }
    src.push(']');
}

fn push_rust_string(src: &mut String, s: &str) {
    src.push('"');
    for ch in s.chars() {
        match ch {
            '\\' => src.push_str("\\\\"),
            '"' => src.push_str("\\\""),
            '\n' => src.push_str("\\n"),
            '\r' => src.push_str("\\r"),
            '\t' => src.push_str("\\t"),
            other => src.push(other),
        }
    }
    src.push('"');
}

fn write_compile_error(out_path: &Path, msg: &str) {
    let mut src = String::new();
    src.push_str("compile_error!(");
    push_rust_string(&mut src, msg);
    src.push_str(");\n");
    fs::write(out_path, src).expect("write migration parity compile_error");
}
